clc;
close all;
clear all;

addpath('C:/Users/Dell/Desktop/ekf-slam-matlab-master/3rd-party', 'C:/Users/Dell/Desktop/ekf-slam-matlab-master/sample-maps', 'C:/Users/Dell/Desktop/ekf-slam-matlab-master/tests','C:/Users/Dell/Desktop/ekf-slam-matlab-master/tools')
mapMakerGUI;

% START Welcome Message

msg_body = [
    'Welcome to the EKF SLAM MATLAB Simulator!' ...
     char(10) char(10) ... %% Line feed, New line
    'To get started, either load one of the pre-made maps located in' ...
    char(10) ...
    'the root folder or build your own using waypoints, landmarks and' ...
    char(10) ...
    'obstacles.' ...
    char(10) char(10) ...
    'This software is developed by Shubham Garg' ...
     char(10) ...
    ];

msg_title = 'Welcome!';

msgbox(msg_body, msg_title);
% --- END Welcome Message